### ISSUE TITLE
Errors encountered while reproducing Adroit environment

### ISSUE THREAD

**Issue by xiaobanni** [gemcollector/RL-ViGen#1]
Thank you for this valuable project. I encountered an issue while trying to reproduce the Adroit environment and would appreciate your help.

I installed the environment using:
```
conda create -n vigen-adroit python=3.8
bash install_adroit.sh
```

However, when executing:
```
cd src/
bash train.sh
```

I encountered an error:
`ModuleNotFoundError: No module named 'mj_envs.hand_manipulation_suite.door_shadowhand_v0'`

After executing the commented-out commands in bash `install_adroit.sh`:
```
git clone https://github.com/watchernyu/rrl-dependencies.git \
   && cd rrl-dependencies \
   && pip install -e mj_envs/. \
   && pip install -e mjrl/.
```

I encountered a new error:
```
Traceback (most recent call last):
  File "/home/xxx/miniconda3/envs/vigen-adroit/lib/python3.8/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/home/xxx/miniconda3/envs/vigen-adroit/lib/python3.8/site-packages/hydra/_internal/utils.py", line 368, in <lambda>
    lambda: hydra.run(
  File "/home/xxx/miniconda3/envs/vigen-adroit/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 110, in run
    _ = ret.return_value
  File "/home/xxx/miniconda3/envs/vigen-adroit/lib/python3.8/site-packages/hydra/core/utils.py", line 233, in return_value
    raise self._return_value
  File "/home/xxx/miniconda3/envs/vigen-adroit/lib/python3.8/site-packages/hydra/core/utils.py", line 160, in run_job
    ret.return_value = task_function(task_cfg)
  File "train_adroit_dhm.py", line 535, in main
    workspace = W(cfg)
  File "train_adroit_dhm.py", line 73, in __init__
    self.setup()
  File "train_adroit_dhm.py", line 143, in setup
    self.train_env = dhm.make_env_RRL(env_name, test_image=False, num_repeats=self.cfg.action_repeat,
  File "/datadrive/xxx/code/RL-ViGen/DHM/dhm/make_env_RRL.py", line 894, in make_env_RRL
    env = DHMEnv(cfg_dict, env_name, test_image, cam_list, num_repeats, num_frames, env_feature_type, device,
  File "/datadrive/xxx/code/RL-ViGen/DHM/dhm/make_env_RRL.py", line 703, in __init__
    env = GymEnv(self.env_name)
  File "/datadrive/xxx/code/RL-ViGen/DHM/dhm/utils.py", line 27, in __init__
    env = gym.make(env)
  File "/home/xxx/miniconda3/envs/vigen-adroit/lib/python3.8/site-packages/gym/envs/registration.py", line 235, in make
    return registry.make(id, **kwargs)
  File "/home/xxx/miniconda3/envs/vigen-adroit/lib/python3.8/site-packages/gym/envs/registration.py", line 128, in make
    spec = self.spec(path)
  File "/home/xxx/miniconda3/envs/vigen-adroit/lib/python3.8/site-packages/gym/envs/registration.py", line 203, in spec
    raise error.UnregisteredEnv("No registered env with id: {}".format(id))
gym.error.UnregisteredEnv: No registered env with id: hammer-adroit-v0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_adroit_dhm.py", line 545, in <module>
    main()
  File "/home/xxx/miniconda3/envs/vigen-adroit/lib/python3.8/site-packages/hydra/main.py", line 49, in decorated_main
    _run_hydra(
  File "/home/xxx/miniconda3/envs/vigen-adroit/lib/python3.8/site-packages/hydra/_internal/utils.py", line 367, in _run_hydra
    run_and_report(
  File "/home/xxx/miniconda3/envs/vigen-adroit/lib/python3.8/site-packages/hydra/_internal/utils.py", line 251, in run_and_report
    assert mdl is not None
AssertionError
```

I suspect it might be a version issue. Do you know how to resolve this? Looking forward to your reply, and thank you in advance.

**Comment by gemcollector** [comment]
Hi, Thanks for receiving your feedback! The issue arose as we have recently been developing a new version, leading to the appearance of some minor bugs. I have now fixed the specified bug, and you can easily install the necessary components by executing the `install_adroit.sh` script. I've also removed any unnecessary installation content. You can now pull the latest version to proceed with the installation. If you have any other questions, please don't hesitate to let me know. Thank you!

**Comment by gemcollector** [comment]
> Thank you for your response. After the modification, the code runs successfully. I only saw the execution method for VRL3 in the Adroit branch. Are there running methods for other algorithms mentioned in the paper?

yea, you can check the `algos` folder.
