### ISSUE TITLE
glfw.GLFWError when running locoeval.py or  ./envs/DMCVGB/test/env_test.py

### ISSUE THREAD

**Issue by qqqqqqqqqqh** [gemcollector/RL-ViGen#13]
Hello, @gemcollector,
I'm trying to reproduce the locomotion results illustrated in Figure 18. The model is obtained by running train.py and the task is unitree stand. When I'm running the locoeval.py, the following problem is occurred:

Traceback (most recent call last):
  File "locoeval.py", line 70, in evaluate
    obs = env.reset()
  File "/home/zhqin/anaconda3/envs/rl-vigen/lib/python3.8/site-packages/dm_control/suite/wrappers/action_scale.py", line 94, in reset
    return self._env.reset()
  File "/home/zhqin/RL_ViGen/envs/DMCVGB/dmcvgb/wrappers.py", line 90, in reset
    return self.env.reset()
  File "/home/zhqin/RL_ViGen/envs/DMCVGB/dmcvgb/wrappers.py", line 213, in reset
    obs = self.env.reset()
  File "/home/zhqin/RL_ViGen/envs/DMCVGB/dmcvgb/wrappers.py", line 329, in reset
    return self._greenscreen(self.env.reset())
  File "/home/zhqin/anaconda3/envs/rl-vigen/lib/python3.8/site-packages/gym/wrappers/time_limit.py", line 26, in reset
    return self.env.reset(**kwargs)
  File "/home/zhqin/anaconda3/envs/rl-vigen/lib/python3.8/site-packages/gym/wrappers/order_enforcing.py", line 18, in reset
    return self.env.reset(**kwargs)
  File "/home/zhqin/RL_ViGen/envs/DMCVGB/dmc2gym/dmc2gym/wrappers.py", line 199, in reset
    obs = self._get_obs(time_step)
  File "/home/zhqin/RL_ViGen/envs/DMCVGB/dmc2gym/dmc2gym/wrappers.py", line 140, in _get_obs
    obs = self.render(
  File "/home/zhqin/RL_ViGen/envs/DMCVGB/dmc2gym/dmc2gym/wrappers.py", line 215, in render
    return self._env.physics.render(
  File "/home/zhqin/anaconda3/envs/rl-vigen/lib/python3.8/site-packages/dm_control/mujoco/engine.py", line 216, in render
    camera = Camera(
  File "/home/zhqin/anaconda3/envs/rl-vigen/lib/python3.8/site-packages/dm_control/mujoco/engine.py", line 709, in __init__
    if self._physics.contexts.mujoco is not None:
  File "/home/zhqin/anaconda3/envs/rl-vigen/lib/python3.8/site-packages/dm_control/mujoco/engine.py", line 540, in contexts
    self._make_rendering_contexts()
  File "/home/zhqin/anaconda3/envs/rl-vigen/lib/python3.8/site-packages/dm_control/mujoco/engine.py", line 523, in _make_rendering_contexts
    render_context = _render.Renderer(
  File "/home/zhqin/anaconda3/envs/rl-vigen/lib/python3.8/site-packages/dm_control/_render/glfw_renderer.py", line 40, in __init__
    super().__init__(max_width, max_height, executor.PassthroughRenderExecutor)
  File "/home/zhqin/anaconda3/envs/rl-vigen/lib/python3.8/site-packages/dm_control/_render/base.py", line 63, in __init__
    ctx.call(self._platform_init, max_width, max_height)
  File "/home/zhqin/anaconda3/envs/rl-vigen/lib/python3.8/site-packages/dm_control/_render/executor/render_executor.py", line 138, in call
    return func(*args, **kwargs)
  File "/home/zhqin/anaconda3/envs/rl-vigen/lib/python3.8/site-packages/dm_control/_render/glfw_renderer.py", line 51, in _platform_init
    self._context = glfw.create_window(width=max_width, height=max_height,
  File "/home/zhqin/anaconda3/envs/rl-vigen/lib/python3.8/site-packages/glfw/__init__.py", line 1168, in create_window
    return _glfw.glfwCreateWindow(width, height, _to_char_p(title),
  File "/home/zhqin/anaconda3/envs/rl-vigen/lib/python3.8/site-packages/glfw/__init__.py", line 628, in errcheck
    _reraise(exc[1], exc[2])
  File "/home/zhqin/anaconda3/envs/rl-vigen/lib/python3.8/site-packages/glfw/__init__.py", line 52, in _reraise
    raise exception.with_traceback(traceback)
  File "/home/zhqin/anaconda3/envs/rl-vigen/lib/python3.8/site-packages/glfw/__init__.py", line 607, in callback_wrapper
    return func(*args, **kwargs)
  File "/home/zhqin/anaconda3/envs/rl-vigen/lib/python3.8/site-packages/glfw/__init__.py", line 820, in _handle_glfw_errors
    raise GLFWError(message)
glfw.GLFWError: (65543) b'GLX: Failed to create context: BadLength (poly request too large or internal Xlib length error)'

Have you ever encountered this problem? How can I solve it?

**Comment by gemcollector** [comment]
Hi, there! I haven't met this issue before. I am not sure whether you could install `glfw==1.12.0` to solve this problem. Otherwise, you should check the libglfw, mesa, OpenGL, etc, these kinds of apt dependencies.

**Comment by qqqqqqqqqqh** [comment]
I annotate the `import wrappers.dmc as dmc` in locoeval.py, and it works. But I don't know why. Whatever, thanks for your reply!
