### ISSUE TITLE
Save video option when training robosuite env

### ISSUE THREAD

**Issue by zichunxx** [gemcollector/RL-ViGen#14]
Hi!

I got the following error when training the `robosuite` env:

```
Traceback (most recent call last):
  File "train.py", line 304, in main
    workspace.train()
  File "/home/xzc/Documents/RL-ViGen/train.py", line 260, in train
    self.eval()
  File "/home/xzc/Documents/RL-ViGen/train.py", line 168, in eval
    self.video_recorder.init(self.eval_env, enabled=(episode == 0))
  File "/home/xzc/Documents/RL-ViGen/video.py", line 25, in init
    self.record(env)
  File "/home/xzc/Documents/RL-ViGen/video.py", line 39, in record
    frame = env.render()
  File "/home/xzc/Documents/RL-ViGen/wrappers/dmc.py", line 183, in __getattr__
    return getattr(self._env, name)
  File "/home/xzc/Documents/RL-ViGen/wrappers/robo_wrapper.py", line 106, in __getattr__
    return getattr(self._env, name)
  File "/home/xzc/mambaforge/envs/pieg/lib/python3.8/site-packages/dm_control/suite/wrappers/action_scale.py", line 103, in __getattr__
    return getattr(self._env, name)
  File "/home/xzc/Documents/RL-ViGen/wrappers/dmc.py", line 67, in __getattr__
    return getattr(self._env, name)
  File "/home/xzc/Documents/RL-ViGen/wrappers/dmc.py", line 149, in __getattr__
    return getattr(self._env, name)
AttributeError: 'Gym2DMC' object has no attribute 'render'
```

It seems that this error was triggered by missing  `__getattr_` in `Gym2DMC` wrapper. Is that right?

**Comment by gemcollector** [comment]
Are you rushing for rebuttal? If so, can you provide me your wechat ID, and we can communicate in a more comfortable way.
